name: CD

#
# Release them when the tag formated like 'v*.*.*' is pushed.
#
on:
  push:
    tags:
    - v*.*.*

jobs:
  #
  # Release to GitHub
  #
  release-GitHub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: |
        dotnet publish -c Release -o ConsoleFlow
      working-directory: ./src/ConsoleFlow
    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_COMPRESS: zip
        GHR_PATH: ./src/ConsoleFlow/ConsoleFlow
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #
  # Release to NuGet
  #
  release-NuGet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Pack package
      run: |
        dotnet pack -c Release
      working-directory: ./src/ConsoleFlow
    - name: Publish package
      run: dotnet nuget push **/*.nupkg  -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
      env:
        NUGET_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
      working-directory: ./src/ConsoleFlow
