name: CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXAMPLE_DIRECTORY: ./src/Example
      DOTNET_VERSION: 3.1.100
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ DOTNET_VERSION }}
    - name: Build example project
      run: |
        dotnet build -c Release
      working-directory: ${{ EXAMPLE_DIRECTORY }}
